<?php

namespace UserBundle\Repository;
use AppBundle\Entity\Category;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $username
     * @return Category|null
     */
    public function findOneByIdOrName($category)
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.id = :id OR u.name = :name')
            ->setParameter('id', $category)
            ->setParameter('name', $category)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function loadCategoryByName($category_name)
    {
        $category = $this->findOneByIdOrName($category_name);
        if(!$category) {
            throw new AccessDeniedException ('No category found for '.$category_name);
        }

        return $category;
    }
}
